2020-12-21 10:55:38|INFO|gpload session started 2020-12-21 10:55:38
2020-12-21 10:55:38|INFO|setting schema 'public' for table 'texttable1'
2020-12-21 10:55:38|INFO|started gpfdist -p 8081 -P 8082 -f "pathto/data_file.txt" -t 30
2020-12-21 10:55:38|INFO|did not find an external table to reuse. creating ext_gpload_reusable_015f190a_4338_11eb_b807_00505698d059
2020-12-21 10:55:38|ERROR|missing data for column "n8"  (seg0 slice1 10.152.8.113:7002 pid=3859)
CONTEXT:  External table ext_gpload_reusable_015f190a_4338_11eb_b807_00505698d059, line 1 of gpfdist://*:pathto/data_file.txt: "aaa|qwer|shjhjg|2012-06-01 15:30:30|1|111|834567|45.67|789.123|7.12345|123.456789"
 encountered while running INSERT INTO public."texttable1" ("s1","s2","s3","dt","n1","n2","n3","n4","n5","n6","n7","n8") SELECT "s1","s2","s3","dt","n1","n2","n3","n4","n5","n6","n7","n8" FROM ext_gpload_reusable_015f190a_4338_11eb_b807_00505698d059
2020-12-21 10:55:38|INFO|rows Inserted          = 0
2020-12-21 10:55:38|INFO|rows Updated           = 0
2020-12-21 10:55:38|INFO|data formatting errors = 0
2020-12-21 10:55:38|INFO|gpload failed
